### ISSUE TITLE
Global function declarations in moku.lua

### ISSUE THREAD

**Issue by britzl** [Jrayp/Moku#2]
There's a few functions (constructor_helper, binary_sum_4bit, binary_sum_8bit etc) that all look like utility functions internal to the moku module but none of them are declared as local functions.

**Comment by Jrayp** [comment]
They are declared local in a forward declaration

```lua
--o  Forward Declarations  o--

local constructor_helper
local binary_sum_8bit
local binary_sum_4bit
local get_type
```

**Comment by britzl** [comment]
Ah, indeed you do!
